"""add session test plan models

Revision ID: 9c50b4a1139a
Revises: 1cef3e68e722
Create Date: 2025-01-16 13:02:27.588117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9c50b4a1139a'
down_revision: Union[str, None] = '1cef3e68e722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_testplan',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xctestrun_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xctestrun_test_configuration', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_on_failure', sa.Boolean(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('repetition_strategy', sa.String(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('recording_strategy', sa.String(), nullable=True),
    sa.Column('recording_start_strategy', sa.String(), nullable=True),
    sa.Column('reinstall_app', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_testplan_step',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('test_cases', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('recording_start_strategy', sa.String(), nullable=True),
    sa.Column('reinstall_app', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('test_plan_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['test_plan_id'], ['session_testplan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_plan_id', 'order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_testplan_step')
    op.drop_table('session_testplan')
    # ### end Alembic commands ###
