"""add trace/xcresult path fields to ExecutionStep

Revision ID: 5be387943a5a
Revises: e547ca06a262
Create Date: 2025-01-21 14:28:55.271489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import api.custom_db_types


# revision identifiers, used by Alembic.
revision: str = '5be387943a5a'
down_revision: Union[str, None] = 'e547ca06a262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xcresult_path', api.custom_db_types.PathType(), nullable=True))
        batch_op.add_column(sa.Column('trace_path', api.custom_db_types.PathType(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_step', schema=None) as batch_op:
        batch_op.drop_column('trace_path')
        batch_op.drop_column('xcresult_path')

    # ### end Alembic commands ###
