"""add Build model

Revision ID: be5b36604c8c
Revises: 03e4e0e9bc41
Create Date: 2025-01-18 14:08:03.390030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import api.custom_db_types


# revision identifiers, used by Alembic.
revision: str = "be5b36604c8c"
down_revision: Union[str, None] = "03e4e0e9bc41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build",
        sa.Column("scheme", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("configuration", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("test_plan", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("xctestrun_path", api.custom_db_types.PathType(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["xc_project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "device_id",
            "scheme",
            "configuration",
            "test_plan",
            name="unique_build",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("build")
    # ### end Alembic commands ###
