"""add session related models

Revision ID: e547ca06a262
Revises: 8b4227f1d910
Create Date: 2025-01-20 13:13:44.655199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import api.custom_db_types


# revision identifiers, used by Alembic.
revision: str = "e547ca06a262"
down_revision: Union[str, None] = "8b4227f1d910"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("build_id", sa.Uuid(), nullable=True),
        sa.Column("device_snapshot", sa.JSON(), nullable=True),
        sa.Column("plan_snapshot", sa.JSON(), nullable=True),
        sa.Column("build_snapshot", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["build_id"], ["build.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["session_testplan.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "execution_step",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_repetition", sa.Integer(), nullable=False),
        sa.Column("plan_step_order", sa.Integer(), nullable=False),
        sa.Column("step_repetition", sa.Integer(), nullable=False),
        sa.Column("recording_start_strategy", sa.String(), nullable=False),
        sa.Column("reinstall_app", sa.Boolean(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("test_cases", sa.JSON(), nullable=True),
        sa.Column("end_on_failure", sa.Boolean(), nullable=False),
        sa.Column(
            "test_target_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id",
            "plan_repetition",
            "plan_step_order",
            "step_repetition",
            name="unique_execution_step",
        ),
    )
    op.create_table(
        "test_result",
        sa.Column("start_time", sa.Float(), nullable=True),
        sa.Column("end_time", sa.Float(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("total_test_count", sa.Integer(), nullable=False),
        sa.Column("passed_tests", sa.Integer(), nullable=False),
        sa.Column("failed_tests", sa.Integer(), nullable=False),
        sa.Column("skipped_tests", sa.Integer(), nullable=False),
        sa.Column("expected_failures", sa.Integer(), nullable=False),
        sa.Column("test_failures", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("execution_step_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_step_id"], ["execution_step.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trace_result",
        sa.Column("export_status", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("execution_step_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_step_id"], ["execution_step.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "core_animation",
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("fps", sa.Float(), nullable=False),
        sa.Column("gpu_utilization", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("execution_step_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_step_id"], ["trace_result.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "process_stdout_err",
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("console_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("execution_step_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_step_id"], ["trace_result.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sysmon",
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("cpu", sa.Float(), nullable=True),
        sa.Column("memory", sa.Float(), nullable=True),
        sa.Column("resident_size", sa.Float(), nullable=True),
        sa.Column("recently_died", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("execution_step_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_step_id"], ["trace_result.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sysmon")
    op.drop_table("process_stdout_err")
    op.drop_table("core_animation")
    op.drop_table("trace_result")
    op.drop_table("test_result")
    op.drop_table("execution_step")
    op.drop_table("session")
    # ### end Alembic commands ###
