"""Fix invalid field on Device Model

Revision ID: 1cef3e68e722
Revises: 672ba89c0404
Create Date: 2025-01-14 18:43:01.007664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1cef3e68e722'
down_revision: Union[str, None] = '672ba89c0404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('product_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('device', 'serial_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('serial_number', sa.VARCHAR(), nullable=False))
    op.drop_column('device', 'product_type')
    # ### end Alembic commands ###
