"""fix TestResult not serializable

Revision ID: f915f6ef5c41
Revises: 5be387943a5a
Create Date: 2025-01-21 15:02:42.838303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import api.custom_db_types
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f915f6ef5c41'
down_revision: Union[str, None] = '5be387943a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sqlite.JSON(),
               type_=sa.Enum('passed', 'failed', 'skipped', 'expected_failure', 'unknown', name='testresult'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.Enum('passed', 'failed', 'skipped', 'expected_failure', 'unknown', name='testresult'),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
