"""add xc_test_cases field to build

Revision ID: 634f106baff9
Revises: f915f6ef5c41
Create Date: 2025-01-27 18:10:59.679264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import api.custom_db_types


# revision identifiers, used by Alembic.
revision: str = '634f106baff9'
down_revision: Union[str, None] = 'f915f6ef5c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xc_test_cases', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.drop_column('xc_test_cases')

    # ### end Alembic commands ###
