import os
import pathlib

import pytest

from core.test_session.xctestrun_parser import read_xctestrun_file


@pytest.fixture(scope="session")
def example_xctestrun_path():
    """
    Fixture to return path to real xctestrun file which was generated by Xcode 16.0 (16A242d).
    """
    current_dir = pathlib.Path(os.path.abspath(__file__)).parent
    return pathlib.Path(current_dir, "..", "..", "test_data", "Example.xctestrun")


@pytest.fixture(scope="session")
def example_xctestrun_content(example_xctestrun_path):
    """
    Fixture to read real xctestrun file which was generated by Xcode 16.0 (16A242d).
    """
    return read_xctestrun_file(example_xctestrun_path.absolute().as_posix())
