import os.path

import pytest

from core.test_session.xctestrun_parser import (
    read_xctestrun_file,
    parse_xctestrun_content,
)


@pytest.fixture(scope="session")
def example_xctestrun_content():
    """
    Fixture to read real xctestrun file which was generated by Xcode 16.0 (16A242d).
    """
    current_dir = os.path.dirname(os.path.abspath(__file__))
    return read_xctestrun_file(
        os.path.join(current_dir, "..", "..", "test_data", "Example.xctestrun")
    )


class TestParseXctestrunContent:
    def test_valid_xctestrun(self, example_xctestrun_content):
        """
        GIVEN valid xctestrun content

        WHEN the content is parsed

        THEN the xctestrun file should be parsed successfully
        """
        parse_xctestrun_content(example_xctestrun_content)


