"""
Contains all the xcode related functionalities. These include:

1. Interacting with Xcode Command Line Tools such as `xcodebuild`, `xctrace`, and `xcresulttool`.
2. Parsing various files and packages generated by these tools such as `.xctestrun`, `.trace`, and `.xcresult`.
"""
